#!/bin/bash

DEFAULT_AOC_YEAR=2015

CURRENT_YEAR=$(date +%Y)

if [ -z "$1" ]; then
  echo "Usage: ./aoc.sh <get|sub> [year] <day>"
  echo "  get: Runs the 'setup.ts' script."
  echo "  sub: Runs the 'run.ts' script."
  echo "  [year]: Optional. The year of the Advent of Code puzzle. Defaults to $DEFAULT_AOC_YEAR."
  echo "  <day>: The day of the Advent of Code puzzle."
  exit 1
fi

COMMAND=$1
YEAR=$DEFAULT_AOC_YEAR 
DAY=""

if [ "$#" -eq 2 ]; then
  DAY=$2
elif [ "$#" -eq 3 ]; then
  YEAR=$2
  DAY=$3
else
  echo "Error: Invalid number of arguments."
  echo "Usage: ./aoc.sh <get|sub> [year] <day>"
  exit 1
fi

if ! [[ "$DAY" =~ ^[0-9]+$ ]]; then
  echo "Error: Day must be a number."
  exit 1
fi

case "$COMMAND" in
  "get")
    echo "Running: ts-node setup.ts $YEAR $DAY"
    ts-node setup.ts "$YEAR" "$DAY"
    ;;
  "sub")
    echo "Running: ts-node run.ts $YEAR $DAY"
    ts-node run.ts "$YEAR" "$DAY"
    ;;
  *)
    echo "Error: Invalid command '$COMMAND'. Use 'get' or 'sub'."
    exit 1
    ;;
esac
